### ISSUE TITLE
[concept] Authenticated API for writing Suggestions

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1037]
Allow people to write Media suggestions, Match Video suggestions via API.

In particular, how would we enable someone to build an app that let you log in to TBA, log in to Chief Delphi (or maybe this is an example of where we really do need imgur support), and upload photos straight from your phone. Someone could snap a photo of every robot in a pit and blast it to TBA right from their phone.

**Comment by SUPERCILEX** [comment]
This feature would be really awesome for https://github.com/SUPERCILEX/Robot-Scouter/issues/83#issuecomment-291277652.

**Comment by phil-lopreiato** [comment]
Now that APIv3 tokens are tied to a user account, we might actually be able to make this. The only downside is that suggestions coming from an app would all show as coming from one user.

Additionally, there appear to have been some [updated to cloud endpoints](https://cloud.google.com/endpoints/docs/authenticating-users) since I wrote the APIs for the Android app a few years ago. If there's an easy way to piggyback off Google's oauth without having to whitelist app Clients IDs (which we do now), that seems like the better approach.
