### ISSUE TITLE
District Points Inaccurate?

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1166]
Reported via email:
```
One of my team members just told me that the NE district rankings as reported through the Blue Alliance API are incorrect. One example is that Team 195 is listed with 103 district points, but the official FIRST rankings lists them with 100 points. My team 1073 is listed in 41st place with 75 points, but the FIRST rankings lists our team in 36th place.
```

**Comment by fangeugene** [comment]
May have to do with this: https://github.com/the-blue-alliance/the-blue-alliance/pull/1163

**Comment by flyingcow93** [comment]
The difference in rank can also be attributed to the way TBA decides what teams are in what district. Currently if team A goes out of district to district B they are now included in district B's ranking data. Discussion here: #1162

**Comment by kensthilaire** [comment]
Thank you Greg for filing this issue on my behalf. Going forward, I'll submit and monitor issues here rather than through email.

Regarding the potential tie with #1162, I can see how that would throw things off. One of the teams that I mentioned in my initial email (FRC 195) did participate in an out of district event and I had reported separately that their district point total was off. I see that a request has been filed with the FRC API to add any district relationship to the team data.

As a short term workaround until that enhancement is implemented could TBA simply pull the district point totals from the FRC data using that API?

**Comment by fangeugene** [comment]
I don't think they have an api for it... Do they?

**Comment by kensthilaire** [comment]
Perhaps that will be the next enhancement request to the FRC API group, for
a more comprehensive set of APIs for district information.

I just had a look at the API doc and it is quite limiting for district
related information (http://docs.frcevents.apiary.io/). The team listings
request does allow for the specification of a district parameter to obtain
the set of teams that belong to a specific district, assuming that you know
that code. If no district code is presented, it looks as though the team
listing data will contain the district to which that team belongs if
appropriate. So, perhaps, the application could take the district
relationship into account when calculating the points for each district and
exclude the points accumulated when the event falls outside of the team's
district.

Ken

**Comment by fangeugene** [comment]
Yep that's a good idea. When initially designing our district calculations,
I was unaware of cross district play.

**Comment by phil-lopreiato** [comment]
Already submitted a feature request. See #1160
