### ISSUE TITLE
Event Wizard: Ability to add YouTube videos to matches

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1213]
Needed for Texas Robotics Invitational on 6/20.

**Comment by phil-lopreiato** [comment]
I'm thinking:
 - Make a new tab 'Match Videos'
 - Populate a list of matches, like 'Match Play' does
 - Show match key and textbox for YT info
    - Do we want to have users input a full YT url, or is just the video id okay? I'm leaning towards url
 - validation, key extraction, posting, etc.

**Comment by gregmarra** [comment]
We could allow key holders to approve suggestions for their own events.
They could write a suggestion then approve it.

**Comment by phil-lopreiato** [comment]
I really like that idea. Maybe we can do both. The trusted api already has an endpoint to add videos to matches, so it would be trivial to add that (and also simplify the submission flow).

But I think there's also value to making a way to display the suggestions for an event and approve them. We'd have to flesh that flow out a little (since we can't go through the admin panel), however
