### ISSUE TITLE
Add List of API Clients to site

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1315]
There are some TBA API clients floating around there, we should compile a list and make a section of the site, so it's easier to develop with. Here are some that I know of that look to be in decent shape

 - https://github.com/phil-lopreiato/tba-apiv2-java
 - https://github.com/chacha/thebluealliance-ruby
 - https://github.com/chacha/thebluealliance-javascript
 - https://github.com/Alexanders101/The-Blue-Alliance-Python-API
 - https://github.com/xNovax/TheBlueAlliance_API

**Comment by nwalters512** [comment]
A few more, for completeness' sake:

* https://github.com/AdiSai/TheBlueAlliance-Java
* https://github.com/tonypeng/TheBlueAllianceJavaAPI
* https://github.com/khanh111/node-thebluealliance
* https://github.com/FRC2834/java-blue-alliance-api

It's fantastic that the community has been able to build these things. While we could continue relying on third parties to build out these libraries, it would be interesting to consider hosting these in the TBA repo and making them an officially supported part of their product. That way, we could help shape the development of these libraries, update them when we change the API, and so on. Of course, it's not really feasible to maintain these things ourselves, but if we give the original developers the appropriate permissions, they could maintain these, and we'd still have a centralized place for development and so on. Obviously, this would all be with the permission of the original developers.

**Comment by chacha** [comment]
@nwalters512 The last three on that list haven't been updated since mid-2014. That, in and of itself, isn't the definitive measure of if an library is worth listing, I just wanted to point of that being maintained and active should be a consideration. 

The tricky part you get to with putting the library under TBA is that it doesn't make a lot of sense to have more than one *official* library per language. If the original developers drop out, now that you've stamped them as the *official* library for that language, you either have to discard the library or pick up the slack (which is probably, like you mention, not super feasible). 

I've seen a number of services that just provide a list of APIs categorized by language, and I think it works best that way. If one of the APIs become outdated, you can just remove it from the list. 

However, I definitely see some upsides to bringing libraries under the TBA organization. I would be willing to put forth my current libraries and continue to maintain them under the TBA flag.

**Comment by phil-lopreiato** [comment]
Yeah, it could go either way. I think the biggest benefit would be for someone using the API to make their own project - if we provide links to some known API implementations, we can save a lot of redundant work. Maybe we just keep a markdown file in the TBA repo we can easily change and link it from the API docs.

**Comment by chacha** [comment]
@phil-lopreiato It might be worth adding it to the `/apicdocs` page on the site. At least for me, that was my first stop when starting to work with the API.

**Comment by nwalters512** [comment]
@chacha Those are good points, especially the one about having to choose/create one "official library" for each language. If the official one doesn't meet someone's needs, they'd have to create a new one or turn to another library, and then we're right back where we started. I think maintaining a list of a number of libraries on the site is a good starting point.

That being said, hosting these libraries would be a great way to have the FIRST community pool their collective time and effort to create some really great products. Not saying that individual developers can't do that as well, but the fact that people have gone out and reinvented the wheel a number of times with these libraries says a lot. Imagine if all those people were working together on a single thing.
