### ISSUE TITLE
Fix team numbers for 2015wmri

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1319]
From the-blue-alliance/the-blue-alliance-data#27:

> yea its is realy team 85 i forgot to change it before uploading it th reson why i put 86 insted of 85 is becuse when we were encrypting routers 85s encryption was not working so we used 86 instead

So we need to change all 86s to 85 for the event.

**Comment by first3234** [comment]
i did fix it if you go to the blue alliance data page and look at the most recent pull request you will see i already fixed it

**Comment by chacha** [comment]
@first3234 Ok, but those changes need to be applied to the actual database. The the-blue-alliance-data is just an export of that.

**Comment by first3234** [comment]
oh ok then never mind i didn't know that it was just a export of the actual data base then use the file i changed on there as a reference of what needs to be changed on the actual  database because all that needs to be changed is on there and if you look at the blue alliance facebook group theres a file that i couldnt add for some reason its the official rankings

**Comment by fangeugene** [comment]
Done.
