### ISSUE TITLE
Fix event stats API cache clearing

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1434]
The endpoint should be cleared when matches update, not when the event updates. Original stats (OPR/DPR/CCWM) were unaffected by this issue (incorrect but lucky) because a change in rankings would update the event, which would clear the cache. However, we now have new stats that depend on Playoff matches, so after rankings stop updating, the cache clearing stops as well.

**Comment by 1fish2** [comment]
Good thinking.

Will the fix for this also clear the cache responsible for the-blue-alliance/the-blue-alliance-android/issues/638? I didn't see any flickering yesterday after alliance-update notification, presumably thanks to the-blue-alliance/the-blue-alliance-android/pull/645, but the alliance list took a long time to show up.

They selected alliances and went to lunch. (When does FIRST post the alliance list?) After lunch and after QF1-1 finished, the “Alliance selections updated” notification arrived. The app showed “No alliance data found” until around the time when it got the QF1-1 score.

**Comment by fangeugene** [comment]
So for 2016 Sacramento Regional, FIRST didn't publish alliance selections until the middle of the Quarterfinal matches (it wasn't on their website either). The issue with them taking a long time to show up is separate. We can temporarily fix it by reducing the cache timer for the endpoint, but the real solution will come with APIv3.

**Comment by 1fish2** [comment]
Is it common this year that FIRST is so late to publish alliance selections?

When that happens, do they publish QF match schedule before alliance selections?

**Comment by phil-lopreiato** [comment]
In general, alliances should be uploaded along with the initial playoff schedule, but if the venue has a spotty Internet connection, the upload will be enqueued until it goes through

**Comment by 1fish2** [comment]
Sacramento had a good enough Internet connection to transmit 2 glorious high def video streams to YouTube, so they can't blame the network.
