### ISSUE TITLE
API v3 Discussion

### ISSUE THREAD

**Issue by synth3tk** [the-blue-alliance/the-blue-alliance#1507]
I know everyone is probably recovering from Robo-hangover or FIRST Flu, but let's start talking API version 3.

What are we looking to improve over the current version?

What new features would we like to introduce?

**Comment by nwalters512** [comment]
One thought I had: when designing APIv3, we should also ask ourselves, "could we duplicate the TBA website using only the data from the API?" If not, we should look at exposing more data (match predictions, "hotness" rankings, etc) via the API. Even if we personally don't use that data immediately in our official clients, other parties might be interested in programmatic access to that data.

Now that we've been working with the Android app for several years and are making a push for native apps (iOS and Windows), we should look at trying to move things that currently require client-side computations to be part of the API proper. 

We currently rely on [Google Cloud Endpoints](https://cloud.google.com/endpoints/) for all mobile app interactions with myTBA. @phil-lopreiato has done most of the work with this, so I don't know a whole lot about it. However, it could be valuable to formally expose myTBA via our API. This could let the FRC community build tools on top of the data users give us about their favorite things in FRC. I don't know what those tools would be exactly, but I'm sure the community could surprise us with novel uses for myTBA data.

**Comment by fangeugene** [comment]
Here's a doc where we were brainstorming ideas last fall.

https://docs.google.com/document/d/19pej_DRaZdWUJKpsYRsM_pJDbB3TZA0CWRJRP7Qu978/edit#heading=h.wffkycnu1k1i

We've added a few things in 2016 (like event stats, predictions) that aren't reflected in the doc yet, but it would be good to get some feedback about the general structure.

**Comment by phil-lopreiato** [comment]
> However, it could be valuable to formally expose myTBA via our API

*Technically* the cloud endpoints interfaces are public, you just need a Google oauth token to interact with them. We've been hesitant in the past about allowing write-access but maybe that's less of a concern with it being backed by Google authentication.

> we should look at trying to move things that currently require client-side computations to be part of the API proper

:heart:

**Comment by fangeugene** [comment]
I don't see a reason for exposing myTBA in a public manner.

**Comment by brandondean** [comment]
I think my number one request is get more data back in a signal request. Single event requests should return teams with them (the idea of a simple model might be enough here) since the entire event object is pretty useless without the teams to back them up (and the same for events being tacked on for team/events).

Also, a search endpoint would be neat. 😃

**Comment by nwalters512** [comment]
> I don't see a reason for exposing myTBA in a public manner.

1. Because we can! #yolo

Like I said, I don't have a particular use case in mind. But if the engineering overhead to make it happen isn't too high, I'm of the opinion that it would be cool to see what, if anything, people could make with it.

Maybe ask Chief to see if there's even a little interest in such a feature?

**Comment by fangeugene** [comment]
How do you do auth if you expose myTBA?

**Comment by phil-lopreiato** [comment]
> How do you do auth if you expose myTBA?

Pass a Google oauth token as a header

**Comment by phil-lopreiato** [comment]
I'd like to propose using [Swagger](https://swagger.io) as the documentation platform for APIv3. It's a specification we can use to define the structure of the API. Then, we can automatically generate [documentation pages](https://github.com/swagger-api/swagger-ui) and [client endpoints](https://github.com/swagger-api/swagger-codegen) for mobile apps.

[Demo](http://petstore.swagger.io/)

**Comment by fangeugene** [comment]
>I think my number one request is get more data back in a signal request. Single event requests should return teams with them (the idea of a simple model might be enough here) since the entire event object is pretty useless without the teams to back them up (and the same for events being tacked on for team/events).

@brandondean I'm revisiting this and now I can't find a good reason for returning all teams with an event, or a reason for the simple model at all. If events are useless without teams, aren't they also useless without matches? Without rankings? Is reducing the number of requests really that big of a deal?

**Comment by brandondean** [comment]
@fangeugene I'm trying to remember my thought process here. I believe the reasoning was that all other event data is also useless without teams. Matches are useless without teams, so are rankings and awards. This is especially confusing with alliances since alliance picks come with the event, but not any meaningful team data with it. So before you can do any real rendering of the alliance data you have to wait for subsequent team request to finish.

**Comment by fangeugene** [comment]
As of now, the plan for APIv3 is to break alliances out of the Event model to be inline with rankings, district points, and stats. That way the Event model only returns logistical information about the event, and all other things are in their own endpoints. Does that change your reasoning?

**Comment by 1fish2** [comment]
Any experience with FB's [**GraphQL** data query language](http://graphql.org/)? I haven't tried it but their case is very compelling.

The client explicitly requests the fields it wants. That makes it easy to evolve clients without deploying server updates or breaking other clients. It's like a SQL "SELECT x, y, z FROM ..." query but for a hierarchy -- a client could ask for Matches with (or without) Teams and request which fields of each to include. It's strongly-typed, so clients needn't do a lot of work to copy JSON data into static-typed Java/Swift objects. It's view-oriented, that is clients can fetch what they need for specific views, which makes them simpler but not "thinner" in the sense of the server dictating presentation, for better or worse.

It's not over-RESTy (vs. Swagger?) in that it doesn't take an API call per object. Multiple API calls would be OK if they go out in a single network request (keep-alive?), but multiple round trips are very slow on high-latency mobile networks. (TCP's exponential backoff was designed to handle congestion, not radio packet collisions.) The server still publishes a schema spec but it sounds like it'd be more flexible and lighter weight than a RESTy spec.

A tradeoff: If fetching a Match includes Teams that are already cached by the client, that takes longer than needed. OTOH if it excludes not-cached Teams, then the client must make a second round trip -- hopefully not 6 more network requests!

With the GraphQL approach (1) the client can request just the needed fields of those Teams, and (2) we can tune the choices of what to include without changing the server's API.

To improve consistency across clients, we can move some client decisions (like, um, [which alliance won Einstein](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/734)) to new fields in the server's reply schema. Maybe there are more bits like that from [Less-thick clients](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/735) to include in the API v3. Ditto for configuration settings unless Firebase is a better way to transmit them. But my thought in 735 of the server controlling making clients hide some fields would have to happen via configuration settings; choosing to omit fields from the response is not the GraphQL way.

**Comment by 1fish2** [comment]
That said, the single thing I most want from API v3 to do is help (if needed) fix [Android app Issue 638](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/638).

It's really annoying to get info via one channel (like a push notification or the match list), then go to the detail screen only to find "No data". Mashing on Refresh doesn't help.

**Comment by 1fish2** [comment]
API v3 can contribute to fixing Android app Issue 638 by:

1. Timestamp each reply so the client can tell when and when not to replace cached data, e.g. data from a match-list request vs. a match request. The timestamp must reflect the data source time, not the reply transmission time.
2. Rethink cache timeouts. Also a timeout would presumably be specific to the GraphQL "query."
3. +?

**Comment by 1fish2** [comment]
Q. Why does the server's caching work well for web clients while causing this big problem for API clients?

Is it because the web page requests/replies combine contents that go out in multiple API replies with separate staleness, cache expirations, and client DB entries? Do its web pages have short time-to-live values? Is it because the server can invalidate its internal DB caches when updates arrive but API replies are stuck with predicted time-to-live values in 3+ levels of network caches?

Would switching to a Firebase API fix that?

**Comment by fangeugene** [comment]
> The client explicitly requests the fields it wants.

I'd like to avoid this if possible because it makes caching a nightmare. This is why the "simple" response was conceived -- to provide a lighter weight response containing only fields in a model that we believe will be commonly used. The question is if this is worth the complexity to save a tiny bit of bandwidth? Maybe this was more relevant when we returned all stats/rankings/alliances as part of the Event model, but those will be separate endpoints in v3 so I don't think it's worth it to implement the simple model now.

**Comment by 1fish2** [comment]
Actually the purpose of requesting specific fields is to greatly boost compatible evolution and enable more client development without having to deploy server changes. From the GraphQL intro:

> In a world of deployed native mobile applications with no forced upgrades, backwards compatibility is a challenge. Facebook, for example, releases apps on a two week fixed cycle and pledges to maintain those apps for at least two years. This means there are at a minimum 52 versions of our clients per platform querying our servers at any given time. Client-specified queries simplifies managing our backwards compatibility guarantees.

Making the response lighter weight is just a minor bonus.

**Comment by fangeugene** [comment]
On [Android app Issue 638](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/638):

Yes, this needs to be fixed.

Server's caching works well because internally we guarantee that if a Model is updated, all caches that reference the model get cleared, so for a given page render everything is consistent. Any caching that happens after rendering the HTML (such as network caches) don't affect the consistency within a page.

This means that it is possible for one page to display outdated data from another (for example a Team page may have the latest match scores but the Event page not have them yet due to cache timeouts). This is the exact issue with API clients; hitting a Team/Event/Matches endpoint may have results for a match, but hitting Event/Matches may not. Timestamping the time of the cached response should provide enough information to the client to fix. I don't know how complicated it would be for the client to use this timestamp.

>Would switching to a Firebase API fix that?

I looked into moving our entire API to the Firebase realtime database, but keeping it in sync with our App engine database is a challenge and it may be cost prohibitive (we do have sponsorship, but I want to make sure it doesn't become infeasible to pay for TBA if we ever lose it). But pricing has changed so it may be worth a revisit.

**Comment by fangeugene** [comment]
> Actually the purpose of requesting specific fields is to greatly boost compatible evolution and enable more client development without having to deploy server changes.

I don't get how requesting specific fields boosts client development. In other words, how does always providing all fields hurt development?

**Comment by phil-lopreiato** [comment]
On GraphQL:
It's pretty awesome and I could see how great it was when I worked on FB4A last summer. However, I'm not sure it's right for TBA. One of the things we _don't_ have is FB resources and scale, nor do we move at the ridiculous speed FB does (they actually release apps weekly now). Our APIs are much more stable and have smaller responses, so there's barely any churn.

Supporting partial responses greatly complicates caching and devalues Google's Edge cache, since the same number of endpoints gets "spread out". Plus, I don't think we have the volume of requests needed to keep all of that warm. @fangeugene, what was our API cache hit rate during the season? I imagine it was pretty good, and reducing it causes more datastore operations, compute time, which all translates to more costs for not much benefit (that I can see, at least).

On https://github.com/the-blue-alliance/the-blue-alliance-android/issues/638:
That's mainly a client side bug - I believe that we can solve that problem entirely by keeping track of `LastModified` timestamps in the db and only overwriting when the data is newer. https://github.com/the-blue-alliance/the-blue-alliance/pull/1513 should also help that, we can mirror those changes inthe app.

**Comment by fangeugene** [comment]
> That's mainly a client side bug - I believe that we can solve that problem entirely by keeping track of LastModified timestamps in the db and only overwriting when the data is newer. #1513 should also help that, we can mirror those changes inthe app.

Oh yeah, LastModified is the server-side cached timestamp.

**Comment by 1fish2** [comment]
Cache-clearing inside the server allow its replies to be always consistent, but somehow they're also timely. That is, it doesn't keep returning a stale "no awards posted" page.

Which part of caching would be a nightmare for field-specific requests? Is it the client side DB?

I guess a client would either have to (1) always request the same fields for each particular object type, or (2) only store the object when it fetches all the fields, or something.

> I don't get how requesting specific fields boosts client development. In other words, how does always providing all fields hurt development?

Always providing all fields means as the server evolves, it returns more and more fields (including object subtrees) that a client has to ignore, and it's tempting to tweak field definitions and hope that doesn't break older clients that are still in the field, and it's tempting to create a simple model that tries to predict which fields aren't needed, ... With client-requested fields, it's easy to add new fields that newer clients can use in place of older fields. Keeping the older, deprecated fields around for a while doesn't cost anything to clients, the network, or server work. It does delay dropping old code from the server.

**Comment by fangeugene** [comment]
> Cache-clearing inside the server allow its replies to be always consistent, but somehow they're also timely. That is, it doesn't keep returning a stale "no awards posted" page.

Certain endpoints (such as Event/Alliances) have a long API cache time (that includes memcache and network caches). That was due to the fact that was being served as part of the Event model. This will no longer be the case in APIv3. Awards also currently has a long cache time (1 hour). We can change it so it is dynamic based on whether the event is in progress.

Part of this caching problem is with push notifications, where new data is pushed to the Android app, but the API endpoints are still stale. Timestamp handling in the app should fix it.

**Comment by fangeugene** [comment]
> Always providing all fields means as the server evolves, it returns more and more fields (including object subtrees) that a client has to ignore, and it's tempting to tweak field definitions and hope that doesn't break older clients that are still in the field, and it's tempting to create a simple model that tries to predict which fields aren't needed

APIv3 avoids nesting subtrees of objects as part of it's design. Everything is either one object or a list of the same object. Ex: Requesting an Event won't get you a list of Teams as one of the fields. It is a completely separate endpoint.

Clients should be able to gracefully handle additional fields, but we shouldn't ever change how a given field is defined.

**Comment by 1fish2** [comment]
> That's mainly a client side bug - I believe that we can solve that problem entirely by keeping track of `LastModified` timestamps in the db and only overwriting when the data is newer.

Also, the server has to ensure the `LastModified` timestamps reflect the upstream data age, say, when it received the data from FMS. Or something like that. I think.

> Certain endpoints (such as Event/Alliances) have a long API cache time (that includes memcache and network caches). That was due to the fact that was being served as part of the Event model. This will no longer be the case in APIv3. Awards also currently has a long cache time (1 hour). We can change it so it is dynamic based on whether the event is in progress.

That helps, but users would still have to mash on the Refresh button much longer than with the web site. Yes?

> Part of this caching problem is with push notifications, where new data is pushed to the Android app, but the API endpoints are still stale. Timestamp handling in the app should fix it.

Push notifications would also need to include `LastModified` timestamps.

> APIv3 avoids nesting subtrees of objects as part of it's design. Everything is either one object or a list of the same object. Ex: Requesting an Event won't get you a list of Teams as one of the fields. It is a completely separate endpoint.

I guess that's OK as long as it doesn't cost multiple round trips to get the data.

**Comment by fangeugene** [comment]
> Also, the server has to ensure the `LastModified` timestamps reflect the upstream data age, say, when it received the data from FMS. Or something like that. I think.

I believe it just needs to be the cache generation time. This is the first layer of cache so it is never out of date.

> That helps, but users would still have to mash on the Refresh button much longer than with the web site. Yes?

The website currently runs on a 5 min cache during an event. So it would depend on what we se tthe API cache to for a given endpoint.

> Push notifications would also need to include `LastModified` timestamps.
Yes

> I guess that's OK as long as it doesn't cost multiple round trips to get the data.

In APIv2 you have to call Team/Events and then Team/Event/Matches. In APIv3 we provide Team/Awards/Year in addition to Team/Event/Awards, so providing /Team/Matches/Year is reasonable.

**Comment by 1fish2** [comment]
> Clients should be able to gracefully handle additional fields, but we shouldn't ever change how a given field is defined.

Yes. It's tempting to just add another value to an enum, or a fourth team name to an alliance.teams array. (Just is a four letter word.) Requesting specific fields means the server can define a new field for the expanded enum or array. That's independent of requesting a hierarchy.

> I believe it [`LastModified` timestamp] just needs to be the cache generation time. This is the first layer of cache so the data it uses to generate the cache is never out of date.

Do you mean the memcache of data from the TBA server's DB? The first layer of cache is in FMS. Can the TBA server's DB suffer from retrograde motion due to those caches? If not, then it does seem sufficient to timestamp values when copied to memcache as long as the data is coherent and the timeouts are short for live events. (+1 for separate object types for objects with different cache lifetimes like `EventDetails`.)

So timestamp management is aided by separate endpoints for separate object types. When returning a list of objects, does the cache provide a single timestamp for the whole list?

I see how partial responses devalue Google's Edge cache and how variable-content responses complicate client caching. A client could store simple models and remaining details in separate tables like `Event` JOIN `EventDetails`. Responses that cache better and enable a shorter timeout (for live events) may be better than responses that are easier to evolve and shorter.

> ... So before you can do any real rendering of the alliance data you have to wait for subsequent team request to finish.

That's an example of slow, extra round trips. There are tradeoffs in getting the relevant teams bundled with the alliance, also in whether the API design or the client code decides what object types to bundle.

What determines whether to call an endpoint `/team/<team_key>/awards/<year>` vs. `/<year>/team/<team_key>/awards` vs. `/team/<team_key>/awards/year/<year>` or `/awards?team=<team_key>&year=<year>`?

**Comment by fangeugene** [comment]
> Do you mean the memcache of data from the TBA server's DB?

CachedResponse is a cached API response stored in the database (and backed by memcache) which gets evicted if anything that makes up the response gets updated. I'm not sure what you mean by retrograde motion in FMS caches.

>So before you can do any real rendering of the alliance data you have to wait for subsequent team request to finish.

> That's an example of slow, extra round trips.

Then perhaps do something like keys vs. full model that the Google doc outlines? My stance is to not provide a keys vs full model option and that that certain queries always returns keys. For example, do you really need all a team's info to render Rankings or Alliance data? Shouldn't the key (and thus the number) suffice? Including the full model in these responses seems useless most of the time.

>What determines whether to call an endpoint?

That's one area I was looking to get feedback on. Obviously consistency is key. Also we shouldn't do query params since a lot of edge caches don't like them.

**Comment by 1fish2** [comment]
Retrograde motion happens when the client retrieves a cached, not-yet-available reply for match scores, alliances, awards, etc., and replaces newer data retrieved from a different endpoint or a push notification. The user may see the new data flash then disappear. Making the client compare timestamps should fix this.

But there must be caches in the FMS and FIRST servers and network. If a TBA request caches some data, then a different request fetches newer data, then seeking details refetches the older cached data, then we'd get retrograde motion. OTOH if no two requests can retrieve overlapping data then only lesser inconsistencies could occur.

> Shouldn't the key (and thus the number) suffice? Including the full model in these responses seems useless most of the time.

I'd think so. So it may be overkill but it would be easier to evolve if the client decides rather than freezing it into the API. Ditto for any "simple model" type splits.

> That's one area I was looking to get feedback on.

Are you up for making the doc more complete than "Major Changes From APIv2"? And for striking out parts that are not currently under consideration (keys only?) and listing questions for feedback?

Suggestion: Make the top component of the request path always be the data type name, e.g. `/awards/team/<team_key>/event/<event_key>` rather than `/team/<team_key>/event/<event_key>/awards`.

Suggestion: Make the query parameters more consistent like `/year/<year>` e.g. `/year/2016` or alternatively `/<year>` in a distinct form like `/y2016`.

**Comment by synth3tk** [comment]
From the FRC Discord:

> is there a way to actually pull a list of teams that competed in a given year?  Or do you have to filter through all team objects?

I think this is actually a really good request, and one I never considered before.

**Comment by fangeugene** [comment]
> is there a way to actually pull a list of teams that competed in a given year? 

That's a planned endpoint

**Comment by ADetectionAlgorithm** [comment]
> That's a planned endpoint

Yay, that's something that would be nice 👍

**Comment by bdaroz** [comment]
Just as thought as I'm working on a Slackbot with the API....

`/team/frcxxx/history/districts` returns a simple array of years and district codes, eg:

```
{
  "2014": "2014ne",
  "2015": "2015ne",
  "2016": "2016ne"
}
```

However the `districts/yyyy` endpoint returns data like this:
```
[
  (snip)
  {
    "name": "North Carolina",
    "key": "nc"
  },
  {
    "name": "New England",
    "key": "ne"
  }
(snip)
]
```

Such that you can't match the team district value to a district key w/o stripping the year off the team value (which is redundant since that's it's index in the array). I'd suggest changing it in v2, but I would expect there are a bunch of uses already managing this in code.

Perhaps in v3 we can align the keys across the API.

**Comment by SUPERCILEX** [comment]
GraphQL is now a thing with GitHub using it: I think it would be a great addition to v3.

**Comment by nwalters512** [comment]
I'd love to use something like GraphQL. The main problem for us, as I understand it, is that caching becomes pretty difficult because clients can pretty much force the server to produce arbitrary responses.

**Comment by SUPERCILEX** [comment]
I know it makes caching difficult, but producing arbitrary responses is what makes GraphQL so beautiful. With v2, I have to query 3 different endpoints for a single screen in my app!

**Comment by nwalters512** [comment]
Don't get me wrong, I'm not denying the utility! It would be especially great for the mobile apps: we could coalesce ~10 requests into one, which would be a huge win in my opinion.

@fangeugene could talk about the backend better than I can though.

**Comment by phil-lopreiato** [comment]
We've discussed GraphQL before (it's actually been around for quite a while, FB has been using it in their mobile apps for almost 5 years now), and here's why I think it isn't worth doing:
 - TBA's dataset isn't a good fit. GraphQL works best with data represented as a graph and that contains some hierarchy between the types. Our data is highly relational - it's flat and refers to objects of different types by the core keys. This is a core design decision that goes all the way down to the way data is stored on the TBA backend, which is optimized for the way app engine's datastore works.
  - As a similar point, our data isn't really hierarchical, which is one of the prime benefits of GraphQL (e.g. saving a ton of *nested* queries). Our data is more self-referential and the more complex pages require a breadth of queries, rather than depth. 
 - It would get near impossible to cache well. TBA relies very heavily on Google's edge cache - this means that many requests at peak times don't actually hit TBA, they're instead served by a Google datacenter. The limitation here is that TBA only has to generate an endpoint once per minute, and that's critical when you take into account the nature of TBA's user patterns: peaky, which makes scaling on demand more expensive. Big companies can handle this load because they have money and resources to throw at a memcache pool in front of the servers. TBA doesn't - our operating costs are surprisingly low and I'm not sure I want to find out what happens when we run without edge caching.
 - Engineering time. GraphQL is complicated and I definitely don't have the time...

However, I'm a fan of the "data wins arguments" mindset - we can try an experiment this season about how much disabling cache actually costs us, and if someone is willing to hack together a proof of concept, we'd definitely take a look

**Comment by bdaroz** [comment]
If we want to talk about caching, and how that gets impacted, we should also take a good look at what gets returned in each call, and how that effects caching. For example `/api/v2/event/2016nytr` includes the alliance selection results. One could reasonably set a *very* long cache validity period for the remainder of the data as the only other piece that really changes prior to/during an event is the webcast value.

I'm taking a hard look at the calls I have to make for the slack bot, and there's a good number of calls I could cut back on, but don't want do because it's a mix of needs-fresh and don't-care-if-stale values, this being the top of the pile. What I'd like to do, and will at some point, maybe after v3, is say this API call is cached and valid for 24-48h at a time unless within 24h of start/end of the event, or the event is ongoing.

Similar thing for a match result. If the match hasn't been played, it could be played earlier, or later than its scheduled time and deserves to be queried more. If it has been played, and is over, say, 8h old, it's not really going to change.

Maybe the way to look at helping apps be "good cache users" is to "suggest" a cache expiration date/time on the result. TBA knows the data, and its update schedule, best, and could communicate that to the clients. That lets us not only judiciously use Last-Modified when we think there may be an update, but simply not make the call at all and use locally cached data (and be *a lot* faster too).

**Comment by phil-lopreiato** [comment]
> If we want to talk about caching, and how that gets impacted, we should also take a good look at what gets returned in each call, and how that effects caching. For example /api/v2/event/2016nytr includes the alliance selection results. One could reasonably set a very long cache validity period for the remainder of the data as the only other piece that really changes prior to/during an event is the webcast value.

This is a great point, and is one of the current areas we can improve on. @fangeugene started migrating the event data with shorter-lived cache times to their own models in https://github.com/the-blue-alliance/the-blue-alliance/pull/1513

When events are live, all the cache expiration times are 61 seconds. I think that's a good fit - matches are posted every ~6 minutes, so if anything, we can make things longer. You can see more details about that where we set the [`Cache-Control` header](https://github.com/the-blue-alliance/the-blue-alliance/blob/130a861c20115480d46b90367ae8b6b036b2cc74/controllers/base_controller.py#L112). You can see more details about that header here: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en#cache-control

**Comment by bdaroz** [comment]
That can certainly be used, and perhaps we need to emphasize the presence of that header to the clients a bit more. But at the same time, we can definitely tweak those values. Eg. a team request is a 24h max-age, and events and matches are 61s. Interestingly team events are 1 hour.

One would expect that if we consider match and event data a 61s age-out, that lists of events, in the current season, would inherit the shortest age-out of the component data, thus the list of current-season events should also expire in 61s.

That said if consensus is that `Cache-Control` is a header we'd like to emphasize for clients to use to avoid making a call to the API, I can take an issue to write that up for v2, so that we can start clients using it now and be ready for v3. I'd offer to dig around in the source to tweak the expiration times but as I've said before, my Python is so rusty I'll need a tetanus shot. 😄

**Comment by phil-lopreiato** [comment]
> One would expect that if we consider match and event data a 61s age-out, that lists of events, in the current season, would inherit the shortest age-out of the component data, thus the list of current-season events should also expire in 61s.

I actually disagree on this. Like I said above, our data isn't really hierarchical like that, it's flat and relational (changing the score of a match doesn't affect its location, for example). So that way, all of those endpoints can have different expiration times, since the data they contain will update with different frequencies.

> That said if consensus is that Cache-Control is a header we'd like to emphasize for clients to use to avoid making a call to the API, I can take an issue to write that up for v2, so that we can start clients using it now and be ready for v3.

I think we should *recommend* clients use `Cache-Control`for those that make a ton of requests (or that poll frequently). I would guess that the only client in use currently that has that volume in the Android app, which already uses the header (@fangeugene can confirm that). But if you'd like to write up something for the apidocs page, that would be awesome.

> I'd offer to dig around in the source to tweak the expiration times but as I've said before, my Python is so rusty I'll need a tetanus shot.

If anyone out there wants to take a stab at tweaking the times, they should first wait for the `EventDetails` model to be active (since it greatly simplifies the problem). Then, the timeouts can differ based on time of the season. After kickoff, event details and the event list can go to longer timeouts, for example. And live event stuff only has to be short as long as the event is active.

**Comment by bdaroz** [comment]
Added PR #1618 to add docs on the Cache-Control header. I'll also be updating the slack bot to use this value in the next week or so. Thanks.

**Comment by bdaroz** [comment]
... and with FRC5881/TBASlackBot#11 the Android app is no longer the only one using the `Cache-Control` header.

**Comment by bdaroz** [comment]
So I started working on documenting a v3 API based on the conversation yesterday and the ideas doc using [Swagger](http://swagger.io) and hit a few bumps before slamming head first into a brick wall.

The first problem is Swagger doesn't allow for non-deterministic results. Thus, we can't have a single `/team/{team_number}/{format}` path where `{format}` is one of `full, short` as they would need to return different models based on the parameter. (Specifically no `oneOf` in the JSON schema.) So the API calls get a bit cluttered with 2 to three (adding `keys` for lists of things) paths for some API endpoints. Not horrible, until....

Then we model the `Match` object and hit the brick wall of `score_breakdown`. This is the epitome of non-deterministic. Even if we modeled the possible values for each year, we'd then need to model different versions of the `Match` model for each year to include the correct `score_breakdown` model for that year, which _still_ doesn't get us there because all we've done is push the problem higher and higher in the model.

If we take this to it's ultimate conclusion we'd have separate endpoints and models for each year for each of `Event`, `Match`, and possibly `Team` (depending on what we include in the `Team` model)

So.. I don't think Swagger is going to work here. If someone wants to take what I started and have a go, let me know and I'll post when I started with as a gist.

**Comment by phil-lopreiato** [comment]
With regard to the contents of models changing year to year, you can just have them be json blobs, and I think that's fine as long as we document the format.

If you want to take a look as an example, here's a swagger spec for APIv2: https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/libTba/swagger/apiv2-swagger.json

**Comment by bdaroz** [comment]
Ugly, but solves a problem... We should still make models for each year though, just to document them.

Forward looking question... Where in the repo would you want to store the swagger specs?

**Comment by phil-lopreiato** [comment]
I think we can store it in the main repo under `static`, so we can just serve the file out

**Comment by 1fish2** [comment]
Will it fix the multiplied endpoints if we use ordinary query parameters
like /team?team_number=1868&format=short instead of overloading the path?

    Jerry

**Comment by bdaroz** [comment]
@1fish2 No, the problem is that the `response` in the Swagger spec must be deterministic. So, for example, we would have 2 models of the `Team` object. The first would be `Team_Simple` and contain the name, team number, and essentials. The second would be `Team` and include `Team_Simple` as well as additional properties.

The problem arises that for `short` requests we must return the `Team_Simple` object, and for `full` requests the fill `Team` object. Swagger does not let us say, in the spec, "Hey, we're going to return either this or that", it must be specific. (Though in 3.0 they seem to be working toward allowing this.)

So it really doesn't matter if the parameter is embedded in the path or the query string.

The other potential solution is to use a single monolithic `Team` model that doesn't populate some fields when requested in a `short` call, however that would make documentation and generated code confusing. (eg "Hey, the return for this says xxx field will be there, but when I call it with `short` it never populates...." -- _or_ the docs are filled with "Field not returned for `short` calls")

**Comment by bdaroz** [comment]
Started PR #1691 for work-in-progress on a v3 swagger spec.

**Comment by ZachOrr** [comment]
Please forgive me if this has already been mentioned (I haven't been keeping up with the discussion), but can we standardize JSON return values for alliances? Some come back with additional information like `backup` and `name`, and some don't. 

Ex (with data): https://www.thebluealliance.com/api/v3/event/2016mike2/alliances
Ex (without): https://www.thebluealliance.com/api/v3/event/2016ohsc/alliances

**Comment by fangeugene** [comment]
Oh that must be an offseason thing. Yeah we'll sanitize it so all fields are included.

**Comment by phil-lopreiato** [comment]
Events 2015 and older won't have them either, since we weren't scraping that data then (we should sanitize/backfill those as well)

**Comment by ThePlasmaGuy** [comment]
v3 question:  Why doesn't the `/team/{team}/event/{event}/status` call have a last_modified header?  I'm working on updating my Python Library to support v3, and my caching method breaks due to the lack of that header key.  I mean, it's super easy to fix on my side by disabling the last_modified caching code if the key doesn't exist, but I still find it weird that every other call has this standard feature except for this call (as far as I can tell at least).

**Comment by ThePlasmaGuy** [comment]
Another question:  When I first started messing around with v3, I was getting coordinates for the estimated location of an FRC team, which is very useful for many different reasons.  However, now when I pull team information from the api, the location keys (like `lat`, `lng`, `gmaps_url`, etc.) are part of the return, but have no value?  Is this purposeful?  These values are very useful and I would very much appreciate their return, but if they are being dropped from the team model, their keys should probably be dropped as well instead of just returning Null for every team.

**Comment by fangeugene** [comment]
The location info worked well overall, but had many edge cases where they were incorrect, so I disabled them so we didn't provide incorrect data. They will be revisited in the future.

**Comment by bdaroz** [comment]
Do we want to leave the fields in the output / spec, or do you want to pull them for now?

**Comment by andrewda** [comment]
If they're just going to be null, I would think pull them and add the fields back when the edge cases are fixed.

**Comment by SUPERCILEX** [comment]
Agreed with @andrewda. Otherwise, it seems like TBA is broken when it technically isn't.

**Comment by bdaroz** [comment]
@fangeugene As I'm working on the docs this week, can we get a ruling on this - in the spec "for future consideration", or pulled from the server response?

**Comment by fangeugene** [comment]
I don't really want to pull it from the response. Just say that it's null for now and will be supported in the future.

**Comment by synth3tk** [comment]
#1691 has been merged. :shipit:
