### ISSUE TITLE
Team social media suggestions does not accept youtube channel

### ISSUE THREAD

**Issue by tsteward** [the-blue-alliance/the-blue-alliance#1519]
When I use http://www.thebluealliance.com/suggest/team/social_media to submit a youtube page, it does not work if the url has "channel" in the url (example: https://www.youtube.com/channel/UCDS0HZhgetGz5Df9wR9M14A). It says that the url is unsupported. Urls with "user" in the url work (example: https://www.youtube.com/user/Uberbots1124).

**Comment by fangeugene** [comment]
What's the fundamental difference between users and channels on YouTube's side??

**Comment by fangeugene** [comment]
@phil-lopreiato note for channels we can't `.lower()` the foreign key.

**Comment by nwalters512** [comment]
According to [this](https://productforums.google.com/forum/#!topic/youtube-creators/ncuRNvAPFFE), a "user" URL is just a human-readable alias for the system-generated channel name.

**Comment by fangeugene** [comment]
Does this mean we could possibly have duplicate Youtubes associated if someone submits both /user and /channel? I don't think it's a huge problem if that's the case.

**Comment by nwalters512** [comment]
Potentially, but there's no easy way to prevent that. There's no easy way to access that full channel key that I can find, so the only case that would happen is if the channel key is added, the owner registers for a custom username, and then re-submits to the system. I wouldn't worry about that.

We may already handle this, but `youtube.com/USERNAME` is also a valid URL. We should make sure to account for that.

**Comment by phil-lopreiato** [comment]
I actually this this one is a wontfix. We should stick with the human readable terms, since those are what get displayed on the team pages (it would be confusing to expose the random id as a "username").

**Comment by nwalters512** [comment]
I think that's fair. That being said, we should still accept URLs like `youtube.com/USERNAME`.

**Comment by tsteward** [comment]
@phil-lopreiato The problems is some youtube channels are not accessible through a "user" url (example: https://www.youtube.com/channel/UCDS0HZhgetGz5Df9wR9M14A)

**Comment by phil-lopreiato** [comment]
> That being said, we should still accept URLs like `youtube.com/USERNAME`

Yup.

> The problems is some youtube channels are not accessible through a "user" url 

If we want to be able to accept channel urls, we need to be able to solve:
 1. How do we store it? I don't want to make another media type to differentiate between a channel and a user, because they *should* be the same thing and the logic just becomes a pain across all platforms.
 2. How do we display it? I think that showing the channel ID or nothing (just an icon) are both unacceptable. If we special case it, it needs to be reflected in (1)
 3. Dealing with duplicates. (a mindset of I hope it won't happen/should be rare just means Murphy's Law will apply more harshly)

Until we can solve all 3 of those issues, I don't think we can accept "channel" urls and it'll have to be a somewhat-arbitrary limitation on our part. We can update the docs to reflect this and recommend that people register a "user" alias to get around it.
