### ISSUE TITLE
API - For the team/frcxxxx API, add the team's district to the result

### ISSUE THREAD

**Issue by bdaroz** [the-blue-alliance/the-blue-alliance#1606]
Currently there are a number of fields returned from the TBA website that do not appear, or match, the API. One of them is the District a team is in, which in this case the API does not return this data at all. 

Eg: https://www.thebluealliance.com/team/88/2016

As a result to recreate this piece of information districts need to have their teams pulled from the API and checked until there is a match, if there is one at all.

I'm sure this would, at scale, create a not-insignificant load on the API and servers, even when using caching and `Last-Modified` headers.

**Comment by phil-lopreiato** [comment]
Check out `team/frcxxxx/history/districts`, you can see which districts teams played in. Docs: http://www.thebluealliance.com/apidocs

The reason we didn't add this info to the team model is because we want to show that district associations are independent between years. This way, we can show /which/ years teams completed in districts, and we have the possibly to deal with representing teams changing districts over time.

**Comment by bdaroz** [comment]
I had missed that one, thanks.
