### ISSUE TITLE
Add DQ info to api v3

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance#1959]
Archive future DQ data and make it accessible to the API v3. Backfill old data if it is still available.

**Comment by bdaroz** [comment]
You can find DQ data already exposed in the API in the various `Ranking` models, as an aggregate value. Is that what you were looking for, or did you have something more specific in mind?

**Comment by inkling16** [comment]
I originally couldn't find anything DQ related in the API, but when I looked through the API documentation again and found cumulative DQ data in the Team_Event_Status_rank model. This is better than nothing, but I would really like to know the matches in which teams were DQed. Does this data already exist somewhere in the API?

**Comment by bdaroz** [comment]
You'll also find it in the `Event_Ranking` model as well. Unfortunately, DQ information isn't exposed elsewhere in the API, neither in v3 or v2. I'd suggest @fangeugene or perhaps @phil-lopreiato could take it from here -- namely I know the FMS (since at least last year) does report team-specific DQs in match results, but I don't know if TBA saves that information.

**Comment by inkling16** [comment]
Thanks!

**Comment by fangeugene** [comment]
Data isn't actually live yet, FYI.

**Comment by inkling16** [comment]
That's fine, I don't need it for any of my current projects.

**Comment by phil-lopreiato** [comment]
There are still two follow-up items here: 

 - Allow setting DQ/surrogate info via the trusted API #2019
    - Potentially update Cheesy Arena to support it (or bug @patfair about it)
 - Backfill this data from FIRST (we should be able to go back to 2015, in theory) #2020

**Comment by fangeugene** [comment]
The data should be live for 2015+
