### ISSUE TITLE
Suggestion: be able to get list of events in progress from the API

### ISSUE THREAD

**Issue by ArthurAllshire** [the-blue-alliance/the-blue-alliance#2028]
I don't think that there is a way to do this at the moment apart from looking at start/end dates, however this is ugly due to timezone and timestamp weirdness. Would be a nice feature for the API.

**Comment by phil-lopreiato** [comment]
Putting this in the API doesn't really solve the timezone problem (you'd just get events active in whatever timezone we pick on the backend). Typically, we've solved this problem by introducing a +/- 1 day margin of error for what we consider "live". This is why we still show webcast links during the day after the webcast ends.

I wrote a version of this for APIv2 (https://github.com/the-blue-alliance/the-blue-alliance/pull/1107) that never went anywhere because it was difficult to get the caching right.

Currently, we don't really have the concept of temporal caching (cached items would automatically have to expire as the event ends), which makes this pretty hard to implement. We definitely don't want to execute a lot of CPU intensive stuff for each API request (we'd prefer to just dump the results of some already cached query). 

So yeah, this is not as easy as it may seem...

**Comment by bdaroz** [comment]
/agree with Phil

First problem is we don't know your Timezone (one of about 1890 or so in TZData at last check), and we only have start/end dates. We don't have the event schedule data (and _FIRST_ doesn't provide it in API) so we don't know if the event starts at 8am local, or 9am local.

Between the timezone and time-of-day problem, you're best just iterating the `/events/yyyy` endpoint and applying an appropriate timezone and an estimate of event time on your end as your use case may well be different than someone else's.

**Comment by phil-lopreiato** [comment]
The best we can likely do here would be to provide the list of events `within_a_day` (as computed on the server).

For caching, we'd have to add the notion of an expiration to `CachedQueryResult`, which will not be a trivial change, although it might be a feature that unblocks other cools stuff. Or, I guess we could just do the filtering serverside from the full event list and dump the result into memcache with an 8 hour timeout.

**Comment by bdaroz** [comment]
True, but it's still a corner-case, and doesn't quite fit the brief, "events in progress". It's an unachievable goal, as written as we have no time-of-day to the start. (Sure we could guess, but for off seasons.... etc.) Looking at the broader issue, you're looking for events that start/end within an arbitrary time, be it "now", "within a day" or, as is used on the TBA front page, "this week". Each requires a different filter, or one set dynamically.

The $64,000 question is, dump the list and cache the heck out of it, making the parsing client-side, or do `n` versions of it server-side and take the computational hit, and the cache miss.

**Comment by bdaroz** [comment]
Given the workaround above, lack of motion on this, time zones (ugh), and inevitable variable definitions for "in progress", I'm going to close this one.
