### ISSUE TITLE
Team information headers different per Page

### ISSUE THREAD

**Issue by NCIS-LEGEND** [the-blue-alliance/the-blue-alliance#2293]
When pulling team information from TBA APIv3, going from page to page, the headers change.

## Expected Behavior
Bug: Consistent headers from page to page when using /teams/{page_num} 

## Current Behavior
Bug: Headers are inconsistent from page to page when using /teams/{page_num}

## Steps to Reproduce (for bugs)
[Google Sheets TBA API v3](https://docs.google.com/spreadsheets/d/1bK012-xPUQuwcJah0RHV4T8ycsx6VH_DAJTixZhkeWY/edit?usp=sharing)

## Context
Trying to compile a list of teams by state on a sheet, but the ordering makes it hard to do any sort of filtering based on the data.

## Your Environment
Google Apps Script Latest

**Comment by bdaroz** [comment]
Can you clarify what the problem is?

As I read this it sounds like you're saying the `/team` and `/teams` endpoints doen't return the same values -- and they don't. The `/team` endpoint returns detailed data on a single team. The `/teams` endpoint returns summary data on a paginated list of teams.

Also, your Expected Behavior lists an endpoint of `/team/{page_num}` when the proper parameter to that endpoint is `/team/{team_key}` Where `{page_num}` is a simple incrementing ordinal integer, and `{team_key}` is a team identifier like `frc254`.

**Comment by NCIS-LEGEND** [comment]
Sorry for the mistype, they are both supposed to be /teams/{page_num} not team. I have updated the original post to reflect that

**Comment by bdaroz** [comment]
Ok, I looked at the spreadsheet you linked but didn't see any headers at all, and no way to compare one page vs another.

What I can tell is that `https://www.thebluealliance.com/api/v3/teams/0` and `https://www.thebluealliance.com/api/v3/teams/1`, for example, do return the same values, in the same order each time.

Whatever script you're running may be altering the return from the API and reordering the values as it puts them into headers/rows in the spreadsheet.

**Comment by NCIS-LEGEND** [comment]
I have put a new example where the headers are being put up by the same function. I put the example of page 0 and 1. It is on sheet 2.

**Comment by NCIS-LEGEND** [comment]
Thanks for the insight, I will look into it to see if there is a work around to it

**Comment by bdaroz** [comment]
Sorry I couldn't help more, but w/o seeing the actual script it's all a best-guess.
