### ISSUE TITLE
Blank Instagram preview

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#2297]
## Expected Behavior
https://www.thebluealliance.com/team/6090 shows a blank preview for https://www.instagram.com/p/BgH9kCEhFUU/

## Current Behavior
![image](https://user-images.githubusercontent.com/57101/43051360-cf0bbcbe-8de6-11e8-9985-7cc400c9d743.png)

Photo is not blank

![image](https://user-images.githubusercontent.com/57101/43051363-d6fc5b9a-8de6-11e8-8820-c87267b5db01.png)

**Comment by SentientBacon** [comment]
This behavior is also being reflected on the iOS app. Instagram images that exist but are blank on the website throw an error due to invalid data from request.

https://www.thebluealliance.com/team/33/2016 (frc33, Killer Bees, 2016 season)

<img width="600" alt="frc66_tba_web" src="https://user-images.githubusercontent.com/8540284/43361377-eb160adc-9281-11e8-9c68-190b6e6fb035.png">
<img width="200" alt="frc66_tba_ios" src="https://user-images.githubusercontent.com/8540284/43361382-010e093e-9282-11e8-9c87-1f8066f0209e.png">

**Comment by gregmarra** [comment]
Thanks for this extra information. This suggests the problem is on the
Instagram side.

**Comment by gregmarra** [comment]
No we should leave this open until we figure out the solution. We may be
able to change what we are doing or report a bug to instagram.

**Comment by sorianog** [comment]
@gregmarra I'd go with the bug route. https://www.instagram.com/developer/support/

**Comment by sorianog** [comment]
Huh, this is interesting....
<img width="701" alt="screen shot 2018-09-22 at 10 40 03 am" src="https://user-images.githubusercontent.com/13261711/45918362-ecd8e300-be53-11e8-9e4a-84cc8c32571f.png">

**Comment by ZachOrr** [comment]
This seems like a larger problem with how we're serving Instagram images/URLs via the API. Those Instagram URLs aren't really meant to be stored, from what I can tell.

I'm surprised no one commenting on this issue tried hitting the URL we were trying to load as a first troubleshooting step. The response `URL signature expired` only takes a [quick Google](https://stackoverflow.com/a/48582513) to figure out what's going on here. It seems Instagram is generating these URL signatures to try to prevent doing what we're doing.

**Comment by ZachOrr** [comment]
I'm not super familiar with the codebase, but it seems like we should be able to run the media parser periodically on Instagram images in order to update their data. It looks like right now it only gets run during media suggestions. I'm not exactly sure how frequently we would have to run it though.

**Comment by dracco1993** [comment]
I've got a fix for this, using the correct API url, but it breaks the JS image carousel we're using.

We could just run the parser from time to time, but my fix is a permanent one, using Instagram's suggested methods.

**Comment by ZachOrr** [comment]
I agree - using their APIs is the right route. Do we know the lifespan of those APIs? It looks like most of the APIs are being deprecated by the end of the year, and the Facebook graph API doesn’t support the read we’re looking to do

**Comment by dracco1993** [comment]
@ZachOrr I can't find if this is going to be deprecated or not, but here's the documentation for what I was purposing changing to:
https://www.instagram.com/developer/embedding/#media_redirect
