### ISSUE TITLE
Hide "Details on FirstInspires" for Offseason Events

### ISSUE THREAD

**Issue by neyre** [the-blue-alliance/the-blue-alliance#2555]
The link to "details on firstinspires" leads to a 404 for offseason events. Perhaps this link should just be hidden for offseason events? Thanks!

![image](https://user-images.githubusercontent.com/1348810/62299734-59385180-b42a-11e9-9552-84f4438dfca2.png)

**Comment by lethosor** [comment]
This issue is specific to this event because someone associated it with "CC" on FRC events, which doesn't actually exist. Some offseasons don't have this field so the link isn't rendered ([example](https://www.thebluealliance.com/event/2019miwrc)) and others have working links ([example](https://www.thebluealliance.com/event/2019mimm)).

**Comment by fangeugene** [comment]
@lethosor is right, this isn't an offseason issue. Issue was an event configuration issue which I fixed.

**Comment by neyre** [comment]
Thanks!
