### ISSUE TITLE
CHS District Greater DC Event #1 Day 2 2022 is just 404ing for the entire event.

### ISSUE THREAD

**Issue by IronCrystal** [the-blue-alliance/the-blue-alliance#4300]
## Expected Behavior
I should be able to load the match data

## Current Behavior
All match links lead to 404

## Steps to Reproduce (for bugs)
https://www.thebluealliance.com/event/2022dc306#results
https://www.thebluealliance.com/match/2022dc306_qm1

## Context
I want to be able to see match data

## Your Environment
The website

**Comment by gregmarra** [comment]
Almost surely a py3 routes issue related to the three digit number in the event id.

**Comment by gregmarra** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/blob/707e9b7d1e34b06cebec1aacdfcc83426773e13b/src/backend/common/models/match.py#L477

`Match.validate_key_name` regex needs to be updated for event codes with more than one number at the end.

`r"^[1-9]\d{3}[a-z]+[0-9]?\_(?:qm|ef\dm|qf\dm|sf\dm|f\dm)\d+$"`
to
``r"^[1-9]\d{3}[a-z]+[0-9]*\_(?:qm|ef\dm|qf\dm|sf\dm|f\dm)\d+$"``
should do it, allowing any number of numbers to be at the end of an Event ID.

Need to add new tests to validate this.

Alternatively, should change this method to split on underscore, first validate an Event key, then validate the match key. Feels wrong to be doing "Event key validation" here, and that's why the Event loads while this fails.

**Comment by IronCrystal** [comment]
Thanks @gregmarra!
