### ISSUE TITLE
District Points wrong from Playoff Performance

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#4401]
## Expected Behavior
For 1502 at 2020mimil

1502 has 30 points from Playoff Performance on https://frc-events.firstinspires.org/2022/team/1502#MIMIL
1502 has 20 points from Playoff Performance on https://www.thebluealliance.com/event/2022mimil#district-points

## Context
Makes district rankings wrong on TBA.

**Comment by ZachOrr** [comment]
Re-running the district points job for this event fixed this issue. I'm unsure about the root cause though. Should be fixed once the caches clear.
<img width="317" alt="Screen Shot 2022-04-06 at 11 14 57 AM" src="https://user-images.githubusercontent.com/516458/162008434-496e222f-7ede-4bc0-859c-fa9cf9c482b0.png">

**Comment by ZachOrr** [comment]
Weirdly this just looks like a situation where the district points calculation for this event happened before we had results for the finals? All 3 members of that alliance are short 10 elim points - but no other members of any alliance have more than they should (so it's not the incorrect score/replay bug we've seen). I'm wondering if this could be related to running the district points calculation using a cached match query that doesn't include the finals? I would need to dig in - but the problem here is non-obvious.

**Comment by gregmarra** [comment]
I have another report for 2022txaus team 2881, where we are behind 10 playoff points. Will check if rerunning fixes.

**Comment by gregmarra** [comment]
Looks corrected in the printed output of re-running the math task. Will confirm when cache clears.
