### ISSUE TITLE
Remove student name from Dean's List Award 

### ISSUE THREAD

**Issue by mdurrani808** [the-blue-alliance/the-blue-alliance#4874]
In the interest of student safety, the students name should be removed from the dean list award listing on the blue alliance. Including the name in relation to the team name releases unnecessary identifying information.

**Comment by dracco1993** [comment]
If I remember correctly, and I will try and find this information, part of the submission for Dean's List is essentially an acknowledgement that the student's name, and inherent association with the team, would be made public, should the student be given the award (similar to the "by participating in an event, you agree to be photographed", kinda thing)
(source: I've helped submit Dean's List nominations in the past)

I could see a reasonable argument for the removal, but on the flip side, I personally know several winners who've been _ecstatic_ when they realized they'd be officially immortalized in the team's history by winning.  I wonder if an opt-out solution would be appropriate, since it's a reasonable concern, but also others want the recognition?

**Comment by fangeugene** [comment]
The names and teams of Dean's List Award winners are published by FIRST at https://frc-events.firstinspires.org/

Unless FIRST makes it a policy to stop publishing names, we will likely continue to mirror the data from FRC Events.
