### ISSUE TITLE
2024 playoff ties don't show winner

### ISSUE THREAD

**Issue by sciencewhiz** [the-blue-alliance/the-blue-alliance#5762]
[2024 ISR #1](https://www.thebluealliance.com/event/2024isde1) Playoff match 12 ended in a tie, with the second tie-breaker (autonomous points) used to break the tie. However, the event page does not reflect the winner, The winning score should be bolded and the playoff bracket should show a win for the team that won the tiebreaker.

![image](https://github.com/the-blue-alliance/the-blue-alliance/assets/4885091/2c970160-521e-46be-8f5a-e74aef09ffb0)
![image](https://github.com/the-blue-alliance/the-blue-alliance/assets/4885091/a872c23b-f329-48be-b9d6-9c173fd8cd4e)

**Comment by trevnels** [comment]
This also shows up in Match 10 at the [FNC Orange County District Event](https://www.thebluealliance.com/event/2024ncwak) and seems to be affecting TBA's playoff district point calculations, since the teams on Alliance 6 (the winner of the tie) were not awarded 7 points after later losing Match 12, though these points are shown on FIRST's side.

![image](https://github.com/the-blue-alliance/the-blue-alliance/assets/25140503/c641ab1f-2d86-4edc-a452-949ff2c51d2a)
![image](https://github.com/the-blue-alliance/the-blue-alliance/assets/25140503/e0894050-8842-47ad-a4e9-a6c21429d9ed)
![image](https://github.com/the-blue-alliance/the-blue-alliance/assets/25140503/d08cc646-5775-4f25-91a8-b390cb51ae52)
